# Generated by Django 6.0.7 on 2026-08-21 18:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kategoriya nomi')),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
            },
        ),
        migrations.CreateModel(
            name='Debtor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='F.I.SH')),
                ('phone', models.CharField(max_length=30, verbose_name='Telefon raqami')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Hozirgi qarz summasi')),
                ('initial_amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name="Boshlang'ich qarz")),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Qarz olingan sana')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Qaytarish muddati')),
                ('status', models.CharField(choices=[('active', 'Qarzdor'), ('paid', "To'langan")], default='active', max_length=20, verbose_name='Holat')),
                ('items_description', models.TextField(blank=True, null=True, verbose_name='Olingan buyumlar / Izoh')),
            ],
            options={
                'verbose_name': 'Qarzdor',
                'verbose_name_plural': 'Qarzdorlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name="To'langan summa")),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name="To'lov vaqti")),
                ('note', models.CharField(blank=True, max_length=255, null=True, verbose_name='Izoh / Usul')),
                ('debtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='store.debtor', verbose_name='Qarzdor')),
            ],
            options={
                'verbose_name': "To'lov",
                'verbose_name_plural': "To'lovlar",
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Mahsulot nomi')),
                ('price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name="Sotish narxi (so'm)")),
                ('cost_price', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name="Tan narxi (so'm)")),
                ('stock', models.IntegerField(default=0, verbose_name="Ombor qoldig'i")),
                ('barcode', models.CharField(blank=True, max_length=50, null=True, verbose_name='Shtrix-kod / SKU')),
                ('image_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Rasm havolasi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='store.category', verbose_name='Kategoriya')),
            ],
            options={
                'verbose_name': 'Mahsulot',
                'verbose_name_plural': 'Mahsulotlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_code', models.CharField(max_length=50, unique=True, verbose_name='Chek raqami')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Sotuv vaqti')),
                ('total_amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Jami summa')),
                ('payment_method', models.CharField(choices=[('naqd', 'Naqd pul'), ('karta', 'Bank kartasi'), ('nasiya', 'Nasiya / Qarz')], default='naqd', max_length=20, verbose_name="To'lov usuli")),
                ('customer_name', models.CharField(default='Xaridor', max_length=150, verbose_name='Xaridor nomi')),
                ('debtor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='store.debtor', verbose_name="Qarzdor (agar nasiya bo'lsa)")),
            ],
            options={
                'verbose_name': 'Sotuv',
                'verbose_name_plural': 'Sotuvlar',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('quantity', models.IntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=0, max_digits=12)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.product')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.sale')),
            ],
        ),
    ]
