# Generated by Django 6.0.7 on 2026-08-21 18:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Taom kategoriyasi (Lavash, Pizza...)')),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Taom Kategoriyasi',
                'verbose_name_plural': 'Taom Kategoriyalari',
            },
        ),
        migrations.CreateModel(
            name='FoodOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_code', models.CharField(max_length=50, unique=True, verbose_name='Buyurtma kodi')),
                ('customer_name', models.CharField(max_length=150, verbose_name='Mijoz ismi')),
                ('phone', models.CharField(max_length=30, verbose_name='Telefon raqam')),
                ('delivery_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dostavka manzili / Stol #')),
                ('total_amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Jami summa')),
                ('payment_method', models.CharField(default='naqd', max_length=20, verbose_name="To'lov usuli")),
                ('order_type', models.CharField(choices=[('delivery', 'Dostavka / Yetkazib berish'), ('pickup', 'Olib ketish / Takeaway'), ('table', 'Zalda / Table Order')], default='delivery', max_length=20, verbose_name='Buyurtma turi')),
                ('status', models.CharField(choices=[('new', 'Yangi Buyurtma 🟡'), ('preparing', 'Tayyorlanmoqda 🍳'), ('delivering', "Yo'lda / Kuryerda 🛵"), ('completed', 'Topshirildi ✅'), ('cancelled', 'Bekor qilindi 🔴')], default='new', max_length=20, verbose_name='Buyurtma holati')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Buyurtma vaqti')),
            ],
            options={
                'verbose_name': 'Taom Buyurtmasi',
                'verbose_name_plural': 'Taom Buyurtmalari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Taom nomi')),
                ('price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name="Narxi (so'm)")),
                ('preparation_time_mins', models.IntegerField(default=15, verbose_name='Tayyorlanish vaqti (daqiqa)')),
                ('is_available', models.BooleanField(default=True, verbose_name='Mavjud (Tugamagan)')),
                ('image_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Rasm URL')),
                ('ingredients', models.TextField(blank=True, null=True, verbose_name='Tarkibi / Retsept')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.foodcategory', verbose_name='Kategoriya')),
            ],
            options={
                'verbose_name': 'Taom / Fast Food',
                'verbose_name_plural': 'Taomlar / Fast Foodlar',
            },
        ),
        migrations.CreateModel(
            name='FoodOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=200)),
                ('quantity', models.IntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=0, max_digits=12)),
                ('food_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.fooditem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.foodorder')),
            ],
        ),
    ]
