# Generated by Django 6.1 on 2026-08-22 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_foodcategory_foodorder_fooditem_foodorderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debtor',
            name='phone',
            field=models.CharField(db_index=True, max_length=30, verbose_name='Telefon raqami'),
        ),
        migrations.AlterField(
            model_name='debtor',
            name='status',
            field=models.CharField(choices=[('active', 'Qarzdor'), ('paid', "To'langan")], db_index=True, default='active', max_length=20, verbose_name='Holat'),
        ),
        migrations.AlterField(
            model_name='foodorder',
            name='order_code',
            field=models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Buyurtma kodi'),
        ),
        migrations.AlterField(
            model_name='foodorder',
            name='status',
            field=models.CharField(choices=[('new', 'Yangi Buyurtma 🟡'), ('preparing', 'Tayyorlanmoqda 🍳'), ('delivering', "Yo'lda / Kuryerda 🛵"), ('completed', 'Topshirildi ✅'), ('cancelled', 'Bekor qilindi 🔴')], db_index=True, default='new', max_length=20, verbose_name='Buyurtma holati'),
        ),
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Shtrix-kod / SKU'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('naqd', 'Naqd pul'), ('karta', 'Bank kartasi'), ('nasiya', 'Nasiya / Qarz')], db_index=True, default='naqd', max_length=20, verbose_name="To'lov usuli"),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sale_code',
            field=models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Chek raqami'),
        ),
    ]
