# Generated by Django 6.1 on 2026-08-23 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_foodorder_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodorder',
            name='telegram_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Telegram ID'),
        ),
    ]
