# Generated by Django 6.0.7 on 2026-08-23 14:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_foodorder_telegram_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Telegram ID')),
                ('first_name', models.CharField(blank=True, default='', max_length=100, verbose_name='Ismi')),
                ('last_name', models.CharField(blank=True, default='', max_length=100, verbose_name='Familiyasi')),
                ('username', models.CharField(blank=True, max_length=100, null=True, verbose_name='@username')),
                ('phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='Telefon raqam')),
                ('photo_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Profil rasmi URL')),
                ('language_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Til kodi')),
                ('is_blocked', models.BooleanField(default=False, verbose_name='Bloklangan')),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Ro'yxatdan o'tgan vaqt")),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Oxirgi faollik')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Izoh (admin uchun)')),
            ],
            options={
                'verbose_name': 'Bot Foydalanuvchisi',
                'verbose_name_plural': 'Bot Foydalanuvchilari',
                'ordering': ['-last_seen'],
            },
        ),
        migrations.AddField(
            model_name='foodorder',
            name='bot_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='store.botuser', verbose_name='Bot foydalanuvchisi'),
        ),
    ]
