# Generated by Django 6.0.7 on 2026-08-23 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_botuser_foodorder_bot_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodorder',
            name='debt_paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Qarz to'langan vaqt"),
        ),
        migrations.AddField(
            model_name='foodorder',
            name='is_debt_paid',
            field=models.BooleanField(default=False, verbose_name="Qarz to'landi"),
        ),
        migrations.AlterField(
            model_name='foodorder',
            name='payment_method',
            field=models.CharField(choices=[('naqd', 'Naqd pul 💵'), ('karta', 'Karta / Payme / Click 💳'), ('qarz', 'Qarz / Kredit 📝')], default='naqd', max_length=20, verbose_name="To'lov usuli"),
        ),
    ]
