# Generated by Django 6.0.7 on 2026-08-23 15:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_foodorder_debt_paid_at_foodorder_is_debt_paid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=150, verbose_name='Mijoz ismi')),
                ('phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='Telefon')),
                ('total_amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name="Qarz summasi (so'm)")),
                ('paid_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name="To'langan summa")),
                ('status', models.CharField(choices=[('unpaid', "To'lanmagan 🔴"), ('partial', "Qisman to'langan 🟡"), ('paid', "To'langan ✅")], db_index=True, default='unpaid', max_length=10, verbose_name='Holat')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Qarz sanasi')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name="To'lov muddati")),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name="To'langan vaqt")),
                ('bot_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debts', to='store.botuser', verbose_name='Bot foydalanuvchisi')),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debt', to='store.foodorder', verbose_name="Bog'liq buyurtma")),
            ],
            options={
                'verbose_name': 'Qarz',
                'verbose_name_plural': 'Qarzdorlar',
                'ordering': ['-created_at'],
            },
        ),
    ]
